### ISSUE TITLE
Installation failure 

### ISSUE THREAD

**Issue by yihaocs** [huggingface/transformers_bloom_parallel#8]
Hi,

I try to install the awesome package by following your ReadME instructions but I can not install successfully. 
The following is the installation error: 

```Bash
  Traceback (most recent call last):
    File "/export/home/miniconda3/envs/bloom/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/export/home/miniconda3/envs/bloom/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/export/home/miniconda3/envs/bloom/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
      return hook(config_settings)
    File "/tmp/pip-build-env-3v60b2_q/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 446, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
    File "/tmp/pip-build-env-3v60b2_q/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-3v60b2_q/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-3v60b2_q/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 483, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-3v60b2_q/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 78, in <module>
  ModuleNotFoundError: No module named 'torch'
  error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /export/home/miniconda3/envs/bloom/bin/python /export/home/miniconda3/envs/bloom/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_editable /tmp/tmpsg843_06
  cwd: /export/home/transformers_bloom_parallel/transformers
  Getting requirements to build editable ... error
error: subprocess-exited-with-error
```

I notice that you mentioned we need to remove torch import in setup.py in transformers of your branch, and I also tried that, but how can I remove the following line:
```Python
from torch.utils.cpp_extension import BuildExtension, CUDAExtension 
```
It seems that the two functions have been used in setup.py 

I have remove extra packages that has the keywords "torch", but that does not help.

Thanks.

**Comment by Narsil** [comment]
Hey sorry about that.

Could you install transformers in editable mode on `main`.

```
git checkout main
pip install -e .
git checkout thomas/add_custom_kernels
python setup.py build_ext --inplace  # This shouldn't complain
```
That should set you up. A cleaner version where all these shenanigans don't have to be made but it's not ready yet
https://github.com/huggingface/transformers/pull/19629/files

**Comment by yihaocs** [comment]
Hi Narsil, 

Thank you very much for the help! I have successfully installed the package following your new instructions! Besides, I have the following several questions: 

- Do you know how much GPU memory do I need to test your serving code? Can I use several V100 (16GB) for testing? 

- Is it possible to extend the current framework to multi-node inference? 

- What is the advantage of your current implementation compared with accelerate and deepspeed? 

Thanks,
Yihao

**Comment by Narsil** [comment]
> Do you know how much GPU memory do I need to test your serving code? Can I use several V100 (16GB) for testing?

You need 8A100(80Go) or 16A100(40Go).

> Is it possible to extend the current framework to multi-node inference?

It's going to be very costly latency-wise. This implementation is memory bandwidth bound. Doable, but not sure if you should. In multinode my hunch is that  PP is going to be better (since you have less network)

I would try to setup each node with a chunk of layers (maximum available). Setup some queue in and out, and make them just run inference as fast as possible on this queue. Nodes would be connected through the queues.

Making `use_cache` work in that setup might prove hard (and it's really important for speed).
Since your system becomes a queue, I would be careful when sending live/varied load towards it. A queue is as fast as your slowest item in the queue. So if 1 inference is slower than the others (longer sequence_length or more batch_size) then it's going to slow down the rest of the queue. It can really slow down everything by orders of magnitude and the only "fix" I know is to smooth the entries to the queue (but it's a delicate and brittle art).

> What is the advantage of your current implementation compared with accelerate and deepspeed?

Faster than accelerate (both latency wise and throughput wise). 
For deepspeed we have similar performance, but we kept having production issues with deepspeed where the kernel would randomly crash. Also this achieves close to DS without using any custom kernel meaning it's more readable/debuggable.

**Comment by yihaocs** [comment]
Hi Narsil, 

Thanks for the detailed clarification. I am quite new and not familiar with the PP inference setup. Do you happen to know how I can actually do the PP for multi-node setup for bloom models? Is there any example repo or code? 

And indeed I found using TP for multi-node inference is quite slow.

Best,
Yihao

**Comment by Narsil** [comment]
>  do the PP for multi-node setup for bloom models? Is there any example repo or code?

Not really, just load the layers manually.

```python
layers = [BloomBlock() for i in range(10)]

def forward(self, in_queue, out_queue):
   for item in in_queue:
       for layer in layers:
           item = layer(item)
       out_queue.put(item)
```

Other than that no, I don't think anyone has tried. But keep in mind performance is still going to be pretty bad compared to having a big machine because of the communication overhead. But PP is going probably to allow you more throughput (might even be comparable to a single machine setup if your network is good enough). Latency on the other hand...

**Comment by yihaocs** [comment]
Hi Narsil,

Really appreciate for answering the question!
